services:
  strapi:
    image: strapi/strapi
    container_name: strapi
    volumes:
      - ./strapi-project:/srv/app
    ports:
      - 1337:1337
  pod: 
    image: theempire/mothership-pod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/mothership-pod-config/env.list:/home/ubuntu/mothership-pod-config/env.list
      - /home/ubuntu/mothership-pod-config/nginx:/nginx

networks:
  backbone:
    driver: bridge
